### ISSUE TITLE
Update SpiderOak One to version 7.5.0

### ISSUE THREAD

**Issue by shbach** [getsolus/3rd-party#21]
New version available:
https://spideroak.support/hc/en-us/articles/360023637011-One-and-Groups-Backup-7-5-0-Release-Notes-February-14-2019

Would appreciate the update, thanks!

**Comment by Staudey** [comment]
Thanks for the reminder!
I am aware of that update, even wrote to the SpiderOak suppor team to get the file added to their repo (so I could get a direct link to it), but then I ran into problems getting the new version to run properly, which I haven't yet found time to figure out and fix.

**Comment by Staudey** [comment]
I think I've finally figured it out.
You can test the new version now.

**Comment by shbach** [comment]
When I run:
`sudo eopkg bi --ignore-safety https://raw.githubusercontent.com/getsolus/3rd-party/master/network/download/spideroak/pspec.xml`

I get:
```
Fetching source from: https://spideroak.com/share/M5XWYZDFNY/retriever/c%3A/Fetch/SpiderOak One/7.5.0/SpiderOakONE_7.5.0_1_amd64.deb
Program terminated.
Could not fetch destination file "https://spideroak.com/share/M5XWYZDFNY/retriever/c%3A/Fetch/SpiderOak One/7.5.0/SpiderOakONE_7.5.0_1_amd64.deb": [Errno 14] HTTPS Error 404 - Not Found
```

Opening the link for the .deb file in a browser works though so I'm not sure what's going on.

**Comment by Staudey** [comment]
Sorry about that, I already had the file in my cache, but when I edited the pspec.xml at some point I converted the space in the URL to an actual space.
Should work now.

**Comment by shbach** [comment]
Works now. Thank you!
