### ISSUE TITLE
Chrome on Linux 	77.0.3865.105

### ISSUE THREAD

**Issue by nur-azhar** [getsolus/3rd-party#31]
noob here I see chrome is not the latest version as per https://www.whatismybrowser.com/guides/the-latest-version/chrome

should i figure out how to send a pull request or ask permission?

**Comment by Staudey** [comment]
I'm pretty sure that page is wrong and the latest version is `77.0.3865.90`, which we have in the repository. `77.0.3865.105` is only for Chrome OS, at least according to the [Chrome Release Blog](https://chromereleases.googleblog.com/2019/09/stable-channel-update-for-chrome-os_27.html).
Regarding your question: If you find that there is actually a newer version of a software out, you can of course simply modify the pspec.xml, test it, and then create a pull request if you want.
