### ISSUE TITLE
Error installing Google Earth

### ISSUE THREAD

**Issue by algent-al** [getsolus/3rd-party#36]
As reported in Solus [Forum](https://discuss.getsol.us/d/3582-googleearth-not-installing), tried it and I confirm that Google Earth has install problem.

![ge-hash](https://user-images.githubusercontent.com/46356616/73266077-76ca5600-41d6-11ea-9965-f94c3ca6568f.png)

**Comment by Staudey** [comment]
Thank you for the issue report, I'll fix it when I get home.

**Comment by Staudey** [comment]
Fixed by 95c56922d434d8457d89497138d3d5f65b4d2074
