### ISSUE TITLE
Upgrade Synology Drive client to 2.x

### ISSUE THREAD

**Issue by samteezy** [getsolus/3rd-party#37]
Hello, I see per [this issue](https://github.com/getsolus/3rd-party/pull/27) that the app called "Synology Cloud Station Drive" may have actually been changed to be "Synology Drive" software that was released in the last year or so. Technically these are different applications so I'm thinking this was an incorrect change to make.

What's a bit odd to me is that the version used is Drive 1.1.4 rather than the 2.0 version that was [released in July](https://www.synology.com/en-us/releaseNote/SynologyDriveClient).

I'm not sure the status of this repo since the description says it's deprecated but updates appear to be occurring, so I propose that Synology Drive is added as a new application to the repo and is based on the 2.x version in order for users to stay current. At the time of this post, the most recent version is 2.0.1-11061.

If we can't add a new app at this time, then at least updating the current app to the newest version would be a good start, and I would hope that the snap that eventually gets built gets the right name set.

**Comment by Staudey** [comment]
That pull request wasn't merged. The software in this repository is still "Synology Cloud Station Drive", as it used to be; and it's at the current version (4.3.2-4450 of 2019-08-06).
This repository is pretty much only in maintenance mode until something better is devised (snap integration in the Software Center, or something to that effect).
