### ISSUE TITLE
Upgrade IntelliJ Idea to v2020.1

### ISSUE THREAD

**Issue by TyPh00nCdr** [getsolus/3rd-party#41]
IntelliJ Idea-CE & IntelliJ Idea Ultimate have been updated to v2020.1:
- [IntelliJ Idea-CE v2020.1](https://download.jetbrains.com/idea/ideaIC-2020.1.tar.gz)
- [IntelliJ Idea Ultimate v2020.1](https://download.jetbrains.com/idea/ideaIU-2020.1.tar.gz)

The current versions in Solus still map to v2019.3.4

**Comment by Staudey** [comment]
Closed by 89084dea743bf40f8473716fecf5c3bd7baa5252
