### ISSUE TITLE
MS core Fonts Install Error

### ISSUE THREAD

**Issue by 0845** [getsolus/3rd-party#46]
Program terminated.
Could not fetch destination file "https://downloads.sourceforge.net/project/corefonts/the%20fonts/final/georgi32.exe": [Errno 14] HTTPS Error 302 - Found

Program terminated.
Cannot open package file: [Errno 2] No such file or directory: 'mscorefonts*.eopkg'

**Comment by Staudey** [comment]
Hello @0845 
Thank you for the report! I will take a look at it when I get home.

**Comment by Staudey** [comment]
Please try again. Seems to have been a temporary server error or failed redirection on Sourceforge's side.
