### ISSUE TITLE
Newest Chrome stable build launches with title bar

### ISSUE THREAD

**Issue by samteezy** [getsolus/3rd-party#59]
Just updated this morning to 93.0.4577.63 via eopkg3p, and the title bar setting is set by default. Never had that happen before.

I was able to untoggle it in Settings (just search for "title bar"), but some users may get surprised by that.

![image](https://user-images.githubusercontent.com/879186/131839647-1b39dff6-e4f2-4877-9f27-32a8b1b830d8.png)

**Comment by Staudey** [comment]
Thanks for the heads-up! I will take a look at it, when I get home.

**Comment by JoshStrobl** [comment]
I appreciate you reaching out about this, however please be mindful that we solely repackage the Debian source provided by Google, and thus the responsibility falls on upstream Google to resolve this issue.
