### ISSUE TITLE
Update Flashplayer NPAPI/PPAPI to 32.0.0.114

### ISSUE THREAD

**Issue by Franckyi** [getsolus/3rd-party#6]
A new Flashplayer version is available : https://fpdownload.adobe.com/get/flashplayer/pdc/32.0.0.114/flash_player_npapi_linux.x86_64.tar.gz
Currently the install process fails because the old version (32.0.0.101) doesn't seem to be available anymore.

**Comment by Staudey** [comment]
Fixed by 894f150ae965ec11d60decef0f2dc703704fce1e
Sorry for the delay
