### ISSUE TITLE
3rd party vscode

### ISSUE THREAD

**Issue by ArthurFleischman** [getsolus/3rd-party#62]
Since we have apps such as chrome, spotify, etc which have open source versions, why dont add the original version of vscode?

**Comment by Staudey** [comment]
See the README

`This repo will not accept NEW packages as we are replacing the majority of them in Solus with Snaps. After we have Snaps integrated in the Software Center we will begin forceful deprecation of this repository.`

**Comment by ArthurFleischman** [comment]
> See the README
> 
> `This repo will not accept NEW packages as we are replacing the majority of them in Solus with Snaps. After we have Snaps integrated in the Software Center we will begin forceful deprecation of this repository.`

Sorry for my lack of attention, and thanks for the quick answer. I'll wait then.
