### ISSUE TITLE
DaVinci Resolve

### ISSUE THREAD

**Issue by acook** [getsolus/3rd-party#63]
I just got DaVinci Resolve working on Solus and I would like to help make a script to deploy it to Solus in the future (it does require a couple of tricks). I think it would be great to add to Solus's one-click 4rd Party installer!

But I've read the readme and seen new programs be denied. This repo has been deprecated for over 5 years but there are some 3rd party apps which just aren't going to be available via snap or flatpak for a long time if ever. 

If I spend the time building the new Resolve package, will it be denied? 

I really want Solus to keep being awesome and I'm trying to help!

**Comment by acook** [comment]
Adding it would look something like this:

```xml
<?xml version="1.0" ?>
<!DOCTYPE PISI SYSTEM "https://getsol.us/standard/pisi-spec.dtd">
<PISI>
    <Source>
        <Name>davinci-resolve</Name>
        <Packager>
            <Name>Anthony M. Cook</Name>
            <Email>github@anthonymcook.com</Email>
        </Packager>
        <Summary>Color grading and non-linear video editor.</Summary>
        <Description>Color grading and non-linear video editor.</Description>
        <License>Custom - </License>
        <Archive sha1sum="2bab18cb8386a0341d3ab1490b5d146c" type="binary">https://sw.blackmagicdesign.com/DaVinciResolve/v17.4.2-1/DaVinci_Resolve_Studio_17.4.2_Linux.zip</Archive>
    </Source>

    <Package>
        <Name>davinci-resolve</Name>
        <Files>
            <Path fileType="executable">/opt/resolve/bin</Path>
            <Path fileType="data">/opt</Path>
        </Files>
        <RuntimeDependencies>
            <Dependency>ocl-icd</Dependency>
        </RuntimeDependencies>
    </Package>

    <History>
        <Update release="1">
            <Date>12-08-2021</Date>
            <Version>17.4.2</Version>
            <Comment>Initial Version</Comment>
            <Name>Anthony M. Cook</Name>
            <Email>github@anthonymcook.com</Email>
        </Update>
    </History>
</PISI>
```

```python
#!/usr/bin/python

# Created For Solus Operating System

from pisi.actionsapi import get, pisitools, shelltools

NoStrip = ["/usr"]
IgnoreAutodep = True

Version = get.srcVERSION()

def setup():
    shelltools.system("pwd")
    shelltools.system("unzip https://sw.blackmagicdesign.com/DaVinciResolve/v%s-1/DaVinci_Resolve_Studio_%s_Linux.zip" % Version)

def install():
    pisitools.insinto("/", "opt")
```

What is missing from the above:

- `plugdev` / `usb` group for current user is required otherwise it will segfault when using the dongle
- Verifying permissions like the deb script (might not be necessary)
- A workaround for blackmagic's keyed downloads (annoying)
- Probably some minor things I overlooked? This is just a sketch

**Comment by JoshStrobl** [comment]
We have no plans on including more in this repo, per the large text on the README.
