### ISSUE TITLE
Sublime Text Update

### ISSUE THREAD

**Issue by glow12121** [getsolus/3rd-party#67]
Hi,

Please consider updating Sublime Text to version 4 that was released around a year ago and is stable. The older version is outdated and contains some bugs, while the newer version does not always work properly when installed via snap.

**Comment by Abhinav1217** [comment]
This is currently talked at https://github.com/getsolus/3rd-party/pull/55. It will be merged soon.

**Comment by Staudey** [comment]
Sorry, seems I never actually responded to this issue report / request because @glow12121 was active in the PR itself too :sweat_smile:
