### ISSUE TITLE
Spotify won't install

### ISSUE THREAD

**Issue by jdrp2311** [getsolus/3rd-party#70]
When trying to install Spotify, the Software Center displays an error message saying that it wasn't able to get the necessary .deb file. Probably its version number has to be updated.
![Captura de tela de 2023-05-31 15-05-21](https://github.com/getsolus/3rd-party/assets/121190190/82ddb2dd-5c68-401f-84cf-a19db7c0f15e)

**Comment by Staudey** [comment]
Thanks! Should be fixed now.
I hate how they almost immediately remove the download link after posting a new version.
