### ISSUE TITLE
Update openjdk dependency for `android-studio`

### ISSUE THREAD

**Issue by chax** [getsolus/3rd-party#75]
Package `android-studio` uses deprecated dependency `openjdk-8`, move it to newer openjdk version.
ref getsolus/packages#166
ref getsolus/solus-sc#264

https://github.com/getsolus/3rd-party/blob/8aec71570da05e58470e1fd3e6f25ee713977b47/programming/android-studio/pspec.xml#L32

**Comment by chax** [comment]
Tagging @Staudey

**Comment by ReillyBrogan** [comment]
@chax It turns out that it doesn't actually need a JDK at all. It ships it's own embedded one.
