### ISSUE TITLE
Sublime Text does not install

### ISSUE THREAD

**Issue by paulscottrobson** [getsolus/3rd-party#82]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

Installing ST using the Software app produces an error

### Steps to reproduce

1. Install Sublime Text from 3rd Party apps

### Expected result

It should install

### Actual result

Message box with u"'Nonetype' object has no attribute 'seek'"

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Budgie

### System details

stem:
  Host: paul-solus Kernel: 6.10.9-302.current arch: x86_64 bits: 64
  Desktop: Budgie v: 10.9.2 Distro: Solus 4.5 resilience
Machine:
  Type: Desktop System: ASUS product: N/A v: N/A serial: <superuser required>
  Mobo: ASUSTeK model: PRIME A520M-A II v: Rev X.0x
    serial: <superuser required> UEFI: American Megatrends v: 3403
    date: 09/20/2023
CPU:
  Info: 8-core AMD Ryzen 7 5700X [MT MCP] speed (MHz): avg: 2200
    min/max: 2200/4662
Graphics:
  Device-1: NVIDIA AD106 [GeForce RTX 4060 Ti] driver: nvidia v: 560.35.03
  Device-2: Logitech Webcam C270 driver: snd-usb-audio,uvcvideo type: USB
  Display: x11 server: X.Org v: 21.1.13 with: Xwayland v: 24.1.2 driver:
    gpu: nvidia,nvidia-nvswitch resolution: 2560x1440~60Hz
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: nvidia mesa v: 560.35.03
    renderer: NVIDIA GeForce RTX 4060 Ti/PCIe/SSE2
Network:
  Device-1: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    driver: r8169
Drives:
  Local Storage: total: 2.75 TiB used: 1.01 TiB (36.5%)
Info:
  Memory: total: 32 GiB available: 31.23 GiB used: 2.08 GiB (6.7%)
  Processes: 368 Uptime: 4m Shell: Bash inxi: 3.3.36

### Other comments

Reinstalled so not broken system I think. Message appears very rapidly so I don't think it downloads ST

**Comment by TraceyC77** [comment]
I get a different error on unstable

```
[u""[Errno 2] No such file or directory: 'install/opt/google/chrome/WildevineCdm/manifest.json'"]
```

**Comment by Staudey** [comment]
This should already be fixed in Unstable and will be fixed on Stable by the time of the next sync.
https://github.com/getsolus/packages/commit/bac9742ac23cea4e70bd701b874c93129234f873
https://github.com/getsolus/eopkg/pull/83

@TraceyC77 Hmm, I'll have to look into that.

**Comment by Staudey** [comment]
Hmm, I get no such error with an up-to-date Unstable system. Perhaps it was fixed by the other change to `pisi`/`eopkg`?

**Comment by TraceyC77** [comment]
Apparently Sublime Text had actually been installed.
After performing a fresh update, I no longer get errors clicking the button to check for updates.

**Comment by Staudey** [comment]
I think it's one of those false-positive symlink errors that `eopkg` likes to spit out ^^

**Comment by Staudey** [comment]
Should be fixed after the sync now.
