### ISSUE TITLE
WTF WPS Office EULA

### ISSUE THREAD

**Issue by kyrios123** [getsolus/3rd-party#9]
Somebody on the forums pointed this in the [WPS Office license](https://www.wps.com/eula)
> (3)If this Software is a WPS Office version for Linux OS, the following apply:
> 
>  1) You are only entitled to install and use this Software on computers meeting the following operating environment requirements as agreed herein:
>  OS: Linux OS produced by China brand enterprises, such as Ubuntu or Ubentu Kylin, Deepin, NeoKylin, NFS China, and New Start
> CPU: X86 or CPU produced by China enterprises such as Loongson, Phytium, SW, Zhaoxin, and MPRC

**Comment by Jacalz** [comment]
That is a remarkably weird license, but it looks like it’s a no go to installing it on Solus 😬

**Comment by Staudey** [comment]
Well, that is unfortunate. WPS Office isn't half bad actually. One more reason to support the LibreOffice effort I suppose ^^

**Comment by Vistaus** [comment]
So?

"Linux OS produced by China brand enterprises, such as Ubuntu"

I get Ubuntu Kylin, but regular Ubuntu isn't created by a China brand enterprise, so their own license is invalid.

**Comment by Vistaus** [comment]
> Well, that is unfortunate. WPS Office isn't half bad actually. One more reason to support the LibreOffice effort I suppose ^^

No, just no. I've had so many issues with LibreOffice in the past, even up to a point where it f*cked up ODT files, the one thing it's supposed to be good at. I've never had any issues with WPS in the past 5 years, so I'll stick to WPS no matter what, no more LibreOffice for me, ever.

**Comment by DataDrake** [comment]
```
1) You shall guarantee that you will guide the third party to distribute the “Product” (including the repacked “Product”, which means that you consent to the distributing of the repacked “Product” by the third party according to the Agreement without paying any charge to you) in the way licensed in the Agreement in a lawful manner. You shall inform the third party that before first use the “Product” (including the repacked “Product”), they should send an email to Kingsoft at this e-mail address: wps_linux@kingsoft.com and filled out their relevant information (including but not limited to the name of the community, contact person, contact number and address), read through and agree to all the terms of the Agreement. Under the above-mentioned condition, the third party has the right to distribute the “Product” (including the repacked “Product”) according to the Agreement. Otherwise, any use (including without limitation repacking and distributing actions) of the “Product” (including the repacked “Product”) shall be deemed to be unauthorized use, and Kingsoft reserves the right to the legal responsibility.
```
Unenforceable. Still valid.

**Comment by JoshStrobl** [comment]
Futhermore:

> You are only allowed to distribute the “Product” provided by Kingsoft as a whole on an AS IS basis. The distributed “Product” shall only be the unmodified complete (including without limitation the whole content of the attached “Kingsoft Software End-User License Agreement” (hereafter referred to as “Kingsoft EULA”)) version provided by Kingsoft that includes all copyright identification

I will be **personally** removing this from 3rd-Party, Software Center, and Help Center doc this week and doing an out-of-band push to stable repo with the updated Software Center.

**Comment by Vistaus** [comment]
Anyway, for those (like me) who still want to receive WPS updates on Solus: WPS is available as a snap: https://snapcraft.io/wps-office

**Comment by JoshStrobl** [comment]
I'm not going to keep a fixed issue open, when it is open, if that's what you're asking.

**Comment by Vistaus** [comment]
> I'm not going to keep a fixed issue open, when it is open, if that's what you're asking.

No, sorry for the confusion. I meant: could you not remove my previous post mentioning the alternative install methods?

**Comment by JoshStrobl** [comment]
> No, sorry for the confusion. I meant: could you not remove my previous post mentioning the alternative install methods?

Sure.

**Comment by JoshStrobl** [comment]
I've now pushed a new Software Center update to unstable that removes WPS Office. In the changelog I reference this commit so individuals can, if they choose, click for more information.

**Comment by KspLite** [comment]
Well, actually there is a big mistake in that EULA. Ubuntu is not a Linux distribution from any China brand. If Ubuntu users can use WPS Office, why is there any problem with Solus? Maybe someone should contact Kingsoft to see whether they're willing to change the EULA.

**Comment by Staudey** [comment]
https://en.m.wikipedia.org/wiki/Ubuntu_Kylin

**Comment by KspLite** [comment]
Sorry, but I live in China Mainland and cannot read Wikipedia. However I do exactly know what Ubuntu Kylin is. It's only a distro maintained by a China brand, based on Ubuntu. Though Ubuntu Kylin is regarded as a Chinese distro, you cannot say that Ubuntu is also from a China brand. So we should be able to say that the logic in WPS EULA doesn't make sense.

**Comment by JoshStrobl** [comment]
It isn't our position to say what does and doesn't "make sense". Their currently EULA is not something we can enforce and by providing WPS Office, our users would be in violation of it.

Locking this issue since the decision to remove it is final.
